# Generated by Django 6.0.2 on 2026-02-23 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_BOOKED", "AppointmentBooked"),
                            ("APPOINTMENT_STATUS", "AppointmentStatus"),
                            ("RESCHEDULE_REQUEST", "RescheduleRequest"),
                            ("PRESCRIPTION_CREATED", "PrescriptionCreated"),
                            ("PHARMACY_STATUS", "PharmacyStatus"),
                            ("LAB_REQUEST_CREATED", "LabRequestCreated"),
                            ("LAB_STATUS", "LabStatus"),
                            ("LAB_RESULT_READY", "LabResultReady"),
                            ("MESSAGE", "Message"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
