# Generated by Django 6.0.2 on 2026-03-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0003_inventoryitem_unique_per_pharmacy"),
        ("pharmacy", "0004_inventoryitem_unique_per_pharmacy"),
    ]

    operations = []
